"""add student profile, grade, language and note models

Revision ID: 538a44e9bdd5
Revises: 4e665f046882
Create Date: 2024-09-17 17:00:49.645984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538a44e9bdd5'
down_revision = '4e665f046882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('address1', sa.String(length=255), nullable=True),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('primary_language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['primary_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('role_group_memberships', schema=None) as batch_op:
        batch_op.drop_constraint('role_group_memberships_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('role_group_memberships_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'role_groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_group_memberships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('role_group_memberships_ibfk_1', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('role_group_memberships_ibfk_2', 'role_groups', ['group_id'], ['id'], ondelete='CASCADE')

    op.drop_table('student_profiles')
    op.drop_table('notes')
    op.drop_table('languages')
    op.drop_table('grades')
    # ### end Alembic commands ###
